name: Python greeting

on:
  push:
    branches: 
      - "main"

permissions:
  contents: read

jobs:
  install-pip-deps:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd # As self-hosted machine is Windows, to bypass security restrictions for PS, cmd is used
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/clone-repo
        with:
          repo-url: https://github.com/mtararujs/python-greetings

      - uses: ./.github/actions/install-py-dpndcs
        with:
          working-directory: python-greetings

  deploy-to-dev:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: install-pip-deps
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/clone-repo
        with:
          repo-url: https://github.com/mtararujs/python-greetings

      - uses: ./.github/actions/deploy-app
        with:
          app-environment: dev
          port: 7001
          working-directory: python-greetings

  tests-on-dev:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: deploy-to-dev
    steps:
      - uses: ./.github/actions/clone-repo
        with:
          repo-url: https://github.com/mtararujs/course-js-api-framework

      - uses: ./.github/actions/install-node-dpndcs
        with:
          working-directory: course-js-api-framework

      - uses: ./.github/actions/run-and-stop-tests
        with:
          working-directory: course-js-api-framework
          app-environment: dev

  deploy-to-staging:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: tests-on-dev
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/clone-repo
        with:
          repo-url: https://github.com/mtararujs/python-greetings

      - uses: ./.github/actions/deploy-app
        with:
          app-environment: staging
          port: 7002
          working-directory: python-greetings

  tests-on-staging:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: deploy-to-staging
    steps:
      - uses: ./.github/actions/clone-repo
        with:
          repo-url: https://github.com/mtararujs/course-js-api-framework

      - uses: ./.github/actions/install-node-dpndcs
        with:
          working-directory: course-js-api-framework

      - uses: ./.github/actions/run-and-stop-tests
        with:
          working-directory: course-js-api-framework
          app-environment: stg

  deploy-to-preprod:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: tests-on-staging
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/clone-repo
        with:
          repo-url: https://github.com/mtararujs/python-greetings

      - uses: ./.github/actions/deploy-app
        with:
          app-environment: preprod
          port: 7003
          working-directory: python-greetings

  tests-on-preprod:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: deploy-to-preprod
    steps:
      - uses: ./.github/actions/clone-repo
        with:
          repo-url: https://github.com/mtararujs/course-js-api-framework

      - uses: ./.github/actions/install-node-dpndcs
        with:
          working-directory: course-js-api-framework

      - uses: ./.github/actions/run-and-stop-tests
        with:
          working-directory: course-js-api-framework
          app-environment: preprod

  deploy-to-prod:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: tests-on-preprod
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/clone-repo
        with:
          repo-url: https://github.com/mtararujs/python-greetings

      - uses: ./.github/actions/deploy-app
        with:
          app-environment: prod
          port: 7004
          working-directory: python-greetings

  tests-on-prod:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: deploy-to-prod
    steps:
      - uses: ./.github/actions/clone-repo
        with:
          repo-url: https://github.com/mtararujs/course-js-api-framework

      - uses: ./.github/actions/install-node-dpndcs
        with:
          working-directory: course-js-api-framework

      - uses: ./.github/actions/run-and-stop-tests
        with:
          working-directory: course-js-api-framework
          app-environment: prod