name: Python greeting

on:
  push:
    branches: 
      - "main"

permissions:
  contents: read

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Clone the repository
        run: |
          git clone https://github.com/mtararujs/python-greetings

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: python-greetings
        run: |
          echo "Installing required dependencies"
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload the cloned repository as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-greetings
          path: python-greetings

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Download the python-greetings repository artifact
        uses: actions/download-artifact@v4
        with:
          name: python-greetings

      - name: Run tests on Dev environment
        run: |
          echo "Deploying to Development"
          pm2 delete greetings-app-dev & set "errorlevel=0"
          pm2 start app.py --name greetings-app-dev --port 7001

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Development environment
        working-directory: python-greetings
        run: |
          echo "Running tests on Development"
          
  deploy-to-staging:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Staging environment
        working-directory: python-greetings
        run: |
          echo "Deploying to Staging"

  tests-on-staging:
    runs-on: self-hosted
    needs: deploy-to-staging
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Staging environment
        working-directory: python-greetings
        run: |
          echo "Running tests on Staging"

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-staging
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Preprod environment
        working-directory: python-greetings
        run: |
          echo "Deploying to Preprod"

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Preprod environment
        working-directory: python-greetings
        run: |
          echo "Running tests on Preprod"

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Prod environment
        working-directory: python-greetings
        run: |
          echo "Deploying to Prod"

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Prod environment
        working-directory: python-greetings
        run: |
          echo "Running tests on Prod"
