name: Python greeting

on:
  push:
    branches: 
      - "main"

permissions:
  contents: read

jobs:
  install-pip-deps:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd # As self-hosted machine is Windows, to bypass security restrictions for PS, cmd is used
    steps:
      - uses: actions/checkout@v4
      - name: Clone the repository
        run: |
          git clone https://github.com/mtararujs/python-greetings python-greetings

      - name: List directory contents
        run: dir python-greetings

      - name: Install dependencies
        working-directory: ${{ github.workspace }}\python-greetings
        run: |
          echo "Installing required dependencies"
          py -m pip install --upgrade pip
          py -m pip install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: install-pip-deps
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Run tests on Dev environment
        run: |
          echo "Deploying to Development"
          pm2 delete greetings-app-dev & set "errorlevel=0"
          pm2 start app.py --name greetings-app-dev --port 7001

  tests-on-dev:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: deploy-to-dev
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Development environment
        working-directory: ${{ github.workspace }}\python-greetings
        run: |
          echo "Running tests on Development"
          
  deploy-to-staging:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: tests-on-dev
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Staging environment
        working-directory: ${{ github.workspace }}\python-greetings
        run: |
          echo "Deploying to Staging"

  tests-on-staging:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: deploy-to-staging
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Staging environment
        working-directory: ${{ github.workspace }}\python-greetings
        run: |
          echo "Running tests on Staging"

  deploy-to-preprod:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: tests-on-staging
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Preprod environment
        working-directory: ${{ github.workspace }}\python-greetings
        run: |
          echo "Deploying to Preprod"

  tests-on-preprod:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: deploy-to-preprod
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Preprod environment
        working-directory: ${{ github.workspace }}\python-greetings
        run: |
          echo "Running tests on Preprod"

  deploy-to-prod:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: tests-on-preprod
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Prod environment
        working-directory: ${{ github.workspace }}\python-greetings
        run: |
          echo "Deploying to Prod"

  tests-on-prod:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    needs: deploy-to-prod
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on Prod environment
        working-directory: ${{ github.workspace }}\python-greetings
        run: |
          echo "Running tests on Prod"
